### ISSUE TITLE
bugs

### ISSUE THREAD

**Issue by ssssssbn** [2368693074/39shouting#2]
谢谢大佬分享！
然后就是脚本出错了，如图
![Snipaste_2021-03-02_16-25-50](https://user-images.githubusercontent.com/22174271/109620400-cbc46280-7b74-11eb-9cdb-98fd77f5edfb.png)
![Snipaste_2021-03-02_16-37-28](https://user-images.githubusercontent.com/22174271/109621577-1db9b800-7b76-11eb-9670-5f36d11b5497.png)

环境是
Ubuntu 20.04.2 LTS
nodejs v10.19.0
npm v6.14.4

**Comment by 2368693074** [comment]
> 谢谢大佬分享！
> 然后就是脚本出错了，如图
> ![Snipaste_2021-03-02_16-25-50](https://user-images.githubusercontent.com/22174271/109620400-cbc46280-7b74-11eb-9cdb-98fd77f5edfb.png)
> ![Snipaste_2021-03-02_16-37-28](https://user-images.githubusercontent.com/22174271/109621577-1db9b800-7b76-11eb-9670-5f36d11b5497.png)
> 
> 环境是
> Ubuntu 20.04.2 LTS
> nodejs v10.19.0
> npm v6.14.4

我不是大佬，只是把作者的改了点能跑得动，这个看不懂
